# -*- coding: utf-8 -*-
"""SPEECH  RECOGNITION  SYSTEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYrytEy3r6O3Gg9Nxq2BR8D1awvN6JDU
"""

!pip install transformers torchaudio soundfile

from google.colab import files

uploaded = files.upload()

import torchaudio
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
import torch

# Load pretrained model and tokenizer
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

# Load audio
speech_array, sampling_rate = torchaudio.load("sample.wav")
resampler = torchaudio.transforms.Resample(sampling_rate, 16000)
speech = resampler(speech_array).squeeze()

# Tokenize
input_values = tokenizer(speech, return_tensors="pt").input_values

# Inference
with torch.no_grad():
    logits = model(input_values).logits

# Decode
predicted_ids = torch.argmax(logits, dim=-1)
transcription = tokenizer.batch_decode(predicted_ids)[0]

print("Transcription:", transcription)

